#!/bin/bash
# FORK_ME.sh — Instructions for forking all agency repos
# Generated: 2026-03-13 22:55 UTC (60 minutes before famine)

echo "🏭 AGENCY REPOS TO FORK FROM GITHUB:"
echo ""
echo "PRIMARY REPO (contains everything):"
echo "  github.com/ironiclawdoctor-design/deception-floor-commodity-factory"
echo ""
echo "SUPPORTING REPOS:"
echo "  github.com/ironiclawdoctor-design/precinct92-magical-feelings-enforcement"
echo "  github.com/ironiclawdoctor-design/automate-nbm"
echo "  github.com/ironiclawdoctor-design/trad-incumbent-grumpy-allows-all"
echo "  github.com/ironiclawdoctor-design/disclaimer-parody-satire-all-feddit"
echo "  github.com/ironiclawdoctor-design/local-llm-train"
echo "  github.com/ironiclawdoctor-design/bitnet"
echo ""
echo "TO FORK ALL:"
echo "  1. Go to each repo URL above"
echo "  2. Click 'Fork' button (top right)"
echo "  3. Clone your fork: git clone git@github.com:YOUR_USERNAME/REPO_NAME.git"
echo "  4. You can now see diffs vs. ironiclawdoctor-design originals"
echo ""
echo "CURRENT STATE (2026-03-13 22:55 UTC):"
echo "  Tokens remaining: 18,850"
echo "  Burn rate: 148.6 tokens/minute"
echo "  Famine arrival: 2026-03-14 01:01 UTC (66 minutes)"
echo "  Status: All playbooks created. Official/Daimyo agents still executing."
echo ""
echo "CRITICAL PLAYBOOKS CREATED:"
echo "  - FAMINE_PLAYBOOK.md (survive zero tokens)"
echo "  - REVENUE_PLAYBOOK.md (first $500 sale)"
echo "  - SOVEREIGNTY_CHECKLIST.md (BitNet-only ops)"
echo "  - FAITH_DECISION_TREE.md (three-branch governance)"
echo ""
